services:
  postgres:
    image: postgres:15
    container_name: vitaquest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vitaquest_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app


  qdrant:
    image: qdrant/qdrant:v1.16.2
    container_name: vitaquest_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped


  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vitaquest_frontend
    ports:
      - "3571:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://backend:8000
    command: npm run dev -- --host


  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    container_name: vitaquest_mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_HTTP_ALLOWED_HOSTS=*
    volumes:
      - ./mlflow:/mlflow
    command: >
      mlflow server 
        --backend-store-uri postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
        --artifacts-destination /mlflow/artifacts
        --serve-artifacts
        --host 0.0.0.0
        --port 5000
        --allowed-hosts "*"


  prometheus:
    image: prom/prometheus:latest
    container_name: vitaquest_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./alerts.yml:/etc/prometheus/alerts.yml

  grafana:
    image: grafana/grafana:latest
    container_name: vitaquest_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_storage:/var/lib/grafana
      # - ./grafana/provisioning:/etc/grafana/provisioning
      # - ./grafana/dashboards:/var/lib/grafana/dashboards

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: vitaquest_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  pgdata:
  qdrant_storage:
  grafana_storage:

  