global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

# rule_files:
#   - "alerts.yml"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093